using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;
using Oracle.ManagedDataAccess.Types;
using System.Text;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Add services
builder.Services.AddSingleton<OllamaService>();
builder.Services.AddSingleton<OracleVectorService>();
builder.Services.AddSingleton<RagService>();

var app = builder.Build();

// Initialize database on startup
using (var scope = app.Services.CreateScope())
{
    var vectorService = scope.ServiceProvider.GetRequiredService<OracleVectorService>();
    await vectorService.InitializeDatabaseAsync();
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

// Endpoints
app.MapPost("/api/ingest", async (IngestRequest request, RagService ragService) =>
{
    await ragService.IngestDocumentAsync(request.Text, request.Metadata);
    return Results.Ok(new { message = "Document ingested successfully" });
});

app.MapPost("/api/chat", async (ChatRequest request, RagService ragService) =>
{
    var response = await ragService.ChatAsync(request.Question);
    return Results.Ok(new { answer = response });
});

app.Run();

// Models
public record IngestRequest(string Text, Dictionary<string, string>? Metadata = null);
public record ChatRequest(string Question);

// Ollama Service
public class OllamaService
{
    private readonly HttpClient _httpClient;
    private readonly string _baseUrl;

    public OllamaService()
    {
        _httpClient = new HttpClient();
        _baseUrl = "http://localhost:11434"; // Default Ollama URL
    }

    public async Task<float[]> GetEmbeddingAsync(string text)
    {
        var request = new
        {
            // Use a model that works well - snowflake-arctic-embed produces good embeddings
            model = "snowflake-arctic-embed:335m",
            prompt = text
        };

        var json = JsonSerializer.Serialize(request);
        var content = new StringContent(json, Encoding.UTF8, "application/json");

        var response = await _httpClient.PostAsync($"{_baseUrl}/api/embeddings", content);
        response.EnsureSuccessStatusCode();

        var responseJson = await response.Content.ReadAsStringAsync();
        var result = JsonSerializer.Deserialize<EmbeddingResponse>(responseJson);
        
        var embedding = result?.embedding ?? throw new Exception("Failed to get embedding");
        
        Console.WriteLine($"Generated embedding with {embedding.Length} dimensions");
        
        return embedding;
    }

    public async Task<string> GenerateResponseAsync(string prompt)
    {
        var request = new
        {
            model = "gemma3:4b", // Use your preferred chat model
            prompt = prompt,
            stream = false
        };

        var json = JsonSerializer.Serialize(request);
        var content = new StringContent(json, Encoding.UTF8, "application/json");

        var response = await _httpClient.PostAsync($"{_baseUrl}/api/generate", content);
        response.EnsureSuccessStatusCode();

        var responseJson = await response.Content.ReadAsStringAsync();
        var result = JsonSerializer.Deserialize<GenerateResponse>(responseJson);
        
        return result?.response ?? throw new Exception("Failed to generate response");
    }

    private record EmbeddingResponse(float[] embedding);
    private record GenerateResponse(string response);
}

// Oracle Vector Database Service
public class OracleVectorService
{
    private readonly string _connectionString;

    public OracleVectorService(IConfiguration configuration)
    {
        _connectionString = configuration.GetConnectionString("Oracle") 
            ?? "Data Source=localhost:1521/FREE;User Id=C##MKA;Password=2001;";
    }

    public async Task InitializeDatabaseAsync()
    {
        using var connection = new OracleConnection(_connectionString);
        await connection.OpenAsync();

        // First, check if table exists
        var checkTableSql = @"
            SELECT COUNT(*) 
            FROM USER_TABLES 
            WHERE TABLE_NAME = 'RAG_DOCUMENTS'";

        using var checkCommand = new OracleCommand(checkTableSql, connection);
        var tableExists = Convert.ToInt32(await checkCommand.ExecuteScalarAsync()) > 0;

        if (!tableExists)
        {
            // Create table with CLOB for embedding (JSON format) - more compatible
            var createTableSql = @"
                CREATE TABLE rag_documents (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    content CLOB,
                    embedding CLOB,
                    metadata CLOB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )";

            using var command = new OracleCommand(createTableSql, connection);
            await command.ExecuteNonQueryAsync();
            
            Console.WriteLine("Created RAG_DOCUMENTS table with CLOB embedding column");
        }

        // Create index on content for basic text search (fallback)
        try
        {
            var createIndexSql = @"
                CREATE INDEX rag_content_idx ON rag_documents (content)
                INDEXTYPE IS CTXSYS.CONTEXT";

            using var indexCommand = new OracleCommand(createIndexSql, connection);
            await indexCommand.ExecuteNonQueryAsync();
            Console.WriteLine("Created content index");
        }
        catch (OracleException ex) when (ex.Number == 955) // Index already exists
        {
            Console.WriteLine("Content index already exists");
        }
        catch (OracleException ex)
        {
            Console.WriteLine($"Warning: Could not create content index: {ex.Message}");
        }
    }

    public async Task InsertDocumentAsync(string content, float[] embedding, Dictionary<string, string>? metadata = null)
    {
        using var connection = new OracleConnection(_connectionString);
        await connection.OpenAsync();

        var metadataJson = metadata != null ? JsonSerializer.Serialize(metadata) : "{}";
        var embeddingJson = JsonSerializer.Serialize(embedding);
        
        var sql = @"
            INSERT INTO rag_documents (content, embedding, metadata)
            VALUES (:content, :embedding, :metadata)";

        using var command = new OracleCommand(sql, connection);
        command.Parameters.Add("content", OracleDbType.Clob).Value = content;
        command.Parameters.Add("embedding", OracleDbType.Clob).Value = embeddingJson;
        command.Parameters.Add("metadata", OracleDbType.Clob).Value = metadataJson;

        await command.ExecuteNonQueryAsync();
    }

    public async Task<List<DocumentResult>> SearchSimilarDocumentsAsync(float[] queryEmbedding, int limit = 5)
    {
        using var connection = new OracleConnection(_connectionString);
        await connection.OpenAsync();

        // Get all documents and calculate similarity in memory
        // For production use, you'd want to implement this more efficiently
        var sql = @"
            SELECT id, content, metadata, embedding
            FROM rag_documents";

        using var command = new OracleCommand(sql, connection);
        var documents = new List<(int Id, string Content, string Metadata, float[] Embedding)>();
        
        using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            var embeddingJson = reader.GetString(3);
            var embedding = JsonSerializer.Deserialize<float[]>(embeddingJson) ?? Array.Empty<float>();
            
            documents.Add((
                Id: reader.GetInt32(0),
                Content: reader.GetString(1),
                Metadata: reader.GetString(2),
                Embedding: embedding
            ));
        }

        // Calculate cosine similarity for each document
        var results = documents
            .Select(doc => new DocumentResult(
                Content: doc.Content,
                Metadata: doc.Metadata,
                Distance: 1.0f - CalculateCosineSimilarity(queryEmbedding, doc.Embedding) // Convert similarity to distance
            ))
            .OrderBy(r => r.Distance) // Lower distance = higher similarity
            .Take(limit)
            .ToList();

        return results;
    }

    private static float CalculateCosineSimilarity(float[] vector1, float[] vector2)
    {
        if (vector1.Length != vector2.Length)
            return 0f;

        float dotProduct = 0f;
        float magnitude1 = 0f;
        float magnitude2 = 0f;

        for (int i = 0; i < vector1.Length; i++)
        {
            dotProduct += vector1[i] * vector2[i];
            magnitude1 += vector1[i] * vector1[i];
            magnitude2 += vector2[i] * vector2[i];
        }

        magnitude1 = (float)Math.Sqrt(magnitude1);
        magnitude2 = (float)Math.Sqrt(magnitude2);

        if (magnitude1 == 0f || magnitude2 == 0f)
            return 0f;

        return dotProduct / (magnitude1 * magnitude2);
    }

    public record DocumentResult(string Content, string Metadata, float Distance);
}

// RAG Service - Main orchestration
public class RagService
{
    private readonly OllamaService _ollama;
    private readonly OracleVectorService _vectorDb;

    public RagService(OllamaService ollama, OracleVectorService vectorDb)
    {
        _ollama = ollama;
        _vectorDb = vectorDb;
    }

    public async Task IngestDocumentAsync(string text, Dictionary<string, string>? metadata = null)
    {
        // Split text into chunks if needed
        var chunks = SplitTextIntoChunks(text, 512);

        foreach (var chunk in chunks)
        {
            var embedding = await _ollama.GetEmbeddingAsync(chunk);
            await _vectorDb.InsertDocumentAsync(chunk, embedding, metadata);
        }
    }

    public async Task<string> ChatAsync(string question)
    {
        // Get embedding for the question
        var questionEmbedding = await _ollama.GetEmbeddingAsync(question);

        // Search for similar documents
        var similarDocs = await _vectorDb.SearchSimilarDocumentsAsync(questionEmbedding, 3);

        // Build context from retrieved documents
        var context = string.Join("\n\n", similarDocs.Select(d => d.Content));

        // Create prompt with context
        var prompt = $@"
Context information:
{context}

Question: {question}

Based on the context information above, please provide a helpful and accurate answer to the question. If the context doesn't contain relevant information, say so.

Answer:";

        // Generate response using Ollama
        return await _ollama.GenerateResponseAsync(prompt);
    }

    private static List<string> SplitTextIntoChunks(string text, int chunkSize)
    {
        var chunks = new List<string>();
        var sentences = text.Split('.', StringSplitOptions.RemoveEmptyEntries);
        var currentChunk = new StringBuilder();

        foreach (var sentence in sentences)
        {
            if (currentChunk.Length + sentence.Length > chunkSize && currentChunk.Length > 0)
            {
                chunks.Add(currentChunk.ToString().Trim());
                currentChunk.Clear();
            }
            currentChunk.Append(sentence.Trim()).Append(". ");
        }

        if (currentChunk.Length > 0)
        {
            chunks.Add(currentChunk.ToString().Trim());
        }

        return chunks.Where(c => !string.IsNullOrWhiteSpace(c)).ToList();
    }
}